name: Cucumber Tests with Allure Report

on:
  push:
    branches: [ main, dev ]
  pull_request:
    branches: [ main, dev ]

jobs:
  ui-tests:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          
      - name: Install dependencies
        run: |
          cd UI_Testing
          npm install
          npm install -g allure-commandline

      - name: Run UI tests
        run: |
          cd UI_Testing
          npm test

      - name: Generate Allure report
        if: always()
        run: |
          cd UI_Testing
          allure generate allure-results --clean -o allure-report

      - name: Upload Allure report
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: allure-report-ui-tests
          path: UI_Testing/allure-report
          retention-days: 30

  api-tests:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v3

      - name: Set up Java
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          
      - name: Install dependencies
        run: |
          cd API_Testing
          npm install
          npm install -g allure-commandline

      - name: Start JAR application
        run: |
          cd API_Testing
          nohup java -jar ./demo-0.0.1-SNAPSHOT.jar &
          sleep 30

      - name: Run API tests
        run: |
          cd API_Testing
          npm test

      - name: Generate Allure report
        if: always()
        run: |
          cd API_Testing
          allure generate allure-results --clean -o allure-report

      - name: Upload Allure report
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: allure-report-api-tests
          path: api-tests/allure-report
          retention-days: 30